gem 'minitest'
require 'minitest/autorun'
require 'minitest/pride'
require './lib/registry'
require './lib/attendee_parser'
require './lib/attendee'
require './lib/printer'
require './lib/command_interpreter'
